### ISSUE TITLE
Display translated result

### ISSUE THREAD

**Issue by ascherdakova** [ascherdakova/MessagesProcessor#18]
Translation is useless if do not show the result to user :)

**Comment by ascherdakova** [comment]
Currently we have the separate dialog, which shows the translated result
First of all we should add push notification, which will ask user if he need the translation for the message
And probably we should replace the dialog entirely with push

**Comment by VasiliyMatutin** [comment]
If separate dialog works as supposed, I prefer to concentrate our efforts on #14 . If not, separate bug should be created. It is not critical anymore
