### ISSUE TITLE
Application crash in the background mode

### ISSUE THREAD

**Issue by VasiliyMatutin** [ascherdakova/MessagesProcessor#22]
_Steps to reproduce_:

- Start application

- Choose tgt & src languages

- Enable service

- Close application & remove it from application stack (onDestroy called)

- Send SMS message to phone

_Expected result_: translate dialog showed 
_Actual result_: application crash

Please note, if application not removed from application stack, everything works fine

[log.txt](https://github.com/ascherdakova/MessagesProcessor/files/1977539/log.txt)

![image](https://user-images.githubusercontent.com/20323228/39672375-bf613150-5131-11e8-9414-825465b5944f.png)

**Comment by VasiliyMatutin** [comment]
Just a brief explanation why this bug submitted to @ascherdakova because some question has been arised. I suspect this bug connected with dialog. To be more precise with line 48 in NetworkTask.java where you try to call context of non-existing application. Is it clear enough now or I should investigate in furter and find a way how to fix it?

**Comment by VasiliyMatutin** [comment]
If you will find that dialod is not a cause of the problem, feel free to reassign it back to me

**Comment by ascherdakova** [comment]
Issue with workaround is not a stopper

**Comment by ascherdakova** [comment]
Deleting activity starting entirely doesn't solve the problem, hence the issue is not in the dialog launch
It crashes before the network task for me right now, bot with anoter error 
[log_e.txt](https://github.com/ascherdakova/MessagesProcessor/files/1977915/log_e.txt)

**Comment by ascherdakova** [comment]
I think I saw the same issue(nullptr for getStringExtra) in your log, but the log is too long to be sure it was a cause

**Comment by VasiliyMatutin** [comment]
Fixed in 1b175285f669aa1bc7a8c426e1eb684a65c9ea5d
Thanks @ascherdakova for your help with investigating this issue

**Comment by ascherdakova** [comment]
Well, deleting dialog now helped (seems like), I'm taking it again

**Comment by ascherdakova** [comment]
Guess it's fixed 07756f0de8ab6dd70c9b4ae8fb71409ea75c9bd3 
It's not reproduced for me now
