### ISSUE TITLE
Languages loading perfomance

### ISSUE THREAD

**Issue by ascherdakova** [ascherdakova/MessagesProcessor#24]
It takes so long to display languages lists.
I'm not sure is it's possible to improve prefomance in this case since we use api, but we need at list to think about it
For me it seems like after adding the progress bar it takes even more time

**Comment by VasiliyMatutin** [comment]
First of all, I can notice that on ADB it takes much longer than on real phone. Not sure how it connected, but it should be tested on real phone before I can make a decision

**Comment by ascherdakova** [comment]
It's more like a suggestion, cuz waiting for 10 mins just pissed me off

**Comment by VasiliyMatutin** [comment]
@ascherdakova I tested it on my phone and languages loaded in a flash, so it seems like an ADB problem. Unfortunately we can do nothing with it
