### ISSUE TITLE
Application shouldnt start activity every time SMS recieved

### ISSUE THREAD

**Issue by VasiliyMatutin** [ascherdakova/MessagesProcessor#26]
Applications window opens every time when SMS recieved and block all screen by itself + adds to application stack. This is not user friendly. May be we should use push notification or rewrite dialog somehow. It is not a critical issue, but we should pay attention to it

**Comment by ascherdakova** [comment]
I used not push but android notifications
Implemented in 82d546b9c367289bd2b10b1b782c39d44c76cbe9
