### ISSUE TITLE
Notification remains on the panel even after opening it

### ISSUE THREAD

**Issue by ascherdakova** [ascherdakova/MessagesProcessor#30]
Notification may be simply skipped by user, it's not quite a problem
But it's not usual behavior for the notification to stay on the panel after clicking on it
Considering the fact that we do not voicing and showing message second time maybe this case may be applicable for us - i mean let the app work this way
We need to decide if we want to get rid of it
I personally support both approaches

**Comment by VasiliyMatutin** [comment]
Implemented in 7d8bf87968833b1ee768c740af2abe60a73afd31
